use crate::util::Letter;

// converts one character to a instance of the Letter struct
pub fn char_to_struct(caractere: char) -> Letter {
    match caractere {
        // the printable ASCII caracters in the official order
        // plus some fancy french diacritics

        // we won't really deal with newlines here
        '\n' => Letter {
            line1: r#" "#,
            line2: r#" "#,
            line3: r#" "#,
            line4: r#" "#,
            line5: r#" "#,
            line6: r#" "#,
        },

        // space ! " ~ $ % & ' ( ) * + , - . /
        ' ' => Letter {
            line1: r#"    "#,
            line2: r#"    "#,
            line3: r#"    "#,
            line4: r#"    "#,
            line5: r#"    "#,
            line6: r#"    "#,
        },
        '!' => Letter {
            line1: r#" _  "#,
            line2: r#"| | "#,
            line3: r#"| | "#,
            line4: r#"|_| "#,
            line5: r#"(_) "#,
            line6: r#"    "#,
        },
        '"' => Letter {
            line1: r#" _ _  "#,
            line2: r#"( | ) "#,
            line3: r#" V V  "#,
            line4: r#"      "#,
            line5: r#"      "#,
            line6: r#"      "#,
        },
        '#' => Letter {
            line1: r#"   _  _    "#,
            line2: r#" _| || |_  "#,
            line3: r#"|_  ..  _| "#,
            line4: r#"|_      _| "#,
            line5: r#"  |_||_|   "#,
            line6: r#"           "#,
        },
        '$' => Letter {
            line1: r#"  _   "#,
            line2: r#" | |  "#,
            line3: r#"/ __) "#,
            line4: r#"\__ \ "#,
            line5: r#"(   / "#,
            line6: r#" |_|  "#,
        },
        '%' => Letter {
            line1: r#" _  __ "#,
            line2: r#"(_)/ / "#,
            line3: r#"  / /  "#,
            line4: r#" / /_  "#,
            line5: r#"/_/(_) "#,
            line6: r#"       "#,
        },
        '&' => Letter {
            line1: r#"  ___    "#,
            line2: r#" ( _ )   "#,
            line3: r#" / _ \/\ "#,
            line4: r#"| (_>  < "#,
            line5: r#" \___/\/ "#,
            line6: r#"         "#,
        },
        '’'=> Letter {
            line1: r#" _  "#,
            line2: r#"( ) "#,
            line3: r#"|/  "#,
            line4: r#"    "#,
            line5: r#"    "#,
            line6: r#"    "#,
        },

        '\'' => Letter {
            line1: r#" _  "#,
            line2: r#"( ) "#,
            line3: r#"|/  "#,
            line4: r#"    "#,
            line5: r#"    "#,
            line6: r#"    "#,
        },
        '(' => Letter {
            line1: r#"  __  "#,
            line2: r#" / /  "#,
            line3: r#"| |   "#,
            line4: r#"| |   "#,
            line5: r#"| |   "#,
            line6: r#" \_\  "#,
        },
        ')' => Letter {
            line1: r#"__   "#,
            line2: r#"\ \  "#,
            line3: r#" | | "#,
            line4: r#" | | "#,
            line5: r#" | | "#,
            line6: r#"/_/  "#,
        },
        '*' => Letter {
            line1: r#"       "#,
            line2: r#"__/\__ "#,
            line3: r#"\    / "#,
            line4: r#"/_  _\ "#,
            line5: r#"  \/   "#,
            line6: r#"       "#,
        },
        '+' => Letter {
            line1: r#"        "#,
            line2: r#"   _    "#,
            line3: r#" _| |_  "#,
            line4: r#"|_   _| "#,
            line5: r#"  |_|   "#,
            line6: r#"        "#,
        },
        ',' => Letter {
            line1: "      ",
            line2: "      ",
            line3: "      ",
            line4: " _    ",
            line5: "( )   ",
            line6: "|/    ",
        },
        '-' => Letter {
            line1: r#"        "#,
            line2: r#"        "#,
            line3: r#" _____  "#,
            line4: r#"|_____| "#,
            line5: r#"        "#,
            line6: r#"        "#,
        },
        '.' => Letter {
            line1: r#"    "#,
            line2: r#"    "#,
            line3: r#"    "#,
            line4: r#" _  "#,
            line5: r#"(_) "#,
            line6: r#"    "#,
        },
        '/' => Letter {
            line1: r#"    __ "#,
            line2: r#"   / / "#,
            line3: r#"  / /  "#,
            line4: r#" / /   "#,
            line5: r#"/_/    "#,
            line6: r#"       "#,
        },

        // numbers and  : ; < = > ? @
        '0' => Letter {
            line1: r#"  ___   "#,
            line2: r#" / _ \  "#,
            line3: r#"| | | | "#,
            line4: r#"| |_| | "#,
            line5: r#" \___/  "#,
            line6: r#"        "#,
        },
        '1' => Letter {
            line1: r#" __  "#,
            line2: r#"/_ | "#,
            line3: r#" | | "#,
            line4: r#" | | "#,
            line5: r#" |_| "#,
            line6: r#"     "#,
        },
        '2' => Letter {
            line1: r#" ____   "#,
            line2: r#"|___ \  "#,
            line3: r#"  __) | "#,
            line4: r#" / __/  "#,
            line5: r#"|_____| "#,
            line6: r#"        "#,
        },
        '3' => Letter {
            line1: r#" _____  "#,
            line2: r#"|___ /  "#,
            line3: r#"  |_ \  "#,
            line4: r#" ___) | "#,
            line5: r#"|____/  "#,
            line6: r#"        "#,
        },
        '4' => Letter {
            line1: r#" _  _    "#,
            line2: r#"| || |   "#,
            line3: r#"| || |_  "#,
            line4: r#"|__   _| "#,
            line5: r#"   |_|   "#,
            line6: r#"         "#,
        },
        '5' => Letter {
            line1: r#" ____   "#,
            line2: r#"| ___|  "#,
            line3: r#"|___ \  "#,
            line4: r#" ___) | "#,
            line5: r#"|____/  "#,
            line6: r#"        "#,
        },
        '6' => Letter {
            line1: r#"  __    "#,
            line2: r#" / /_   "#,
            line3: r#"| '_ \  "#,
            line4: r#"| (_) | "#,
            line5: r#" \___/  "#,
            line6: r#"        "#,
        },
        '7' => Letter {
            line1: r#" _____  "#,
            line2: r#"|___  | "#,
            line3: r#"   / /  "#,
            line4: r#"  / /   "#,
            line5: r#" /_/    "#,
            line6: r#"        "#,
        },
        '8' => Letter {
            line1: r#"  ___   "#,
            line2: r#" ( _ )  "#,
            line3: r#" / _ \  "#,
            line4: r#"| (_) | "#,
            line5: r#" \___/  "#,
            line6: r#"        "#,
        },
        '9' => Letter {
            line1: r#"  ___   "#,
            line2: r#" / _ \  "#,
            line3: r#"| (_) | "#,
            line4: r#" \__, | "#,
            line5: r#"   /_/  "#,
            line6: r#"        "#,
        },
        ':' => Letter {
            line1: r#"    "#,
            line2: r#" _  "#,
            line3: r#"(_) "#,
            line4: r#" _  "#,
            line5: r#"(_) "#,
            line6: r#"    "#,
        },
        ';' => Letter {
            line1: r#"    "#,
            line2: r#" _  "#,
            line3: r#"(_) "#,
            line4: r#" _  "#,
            line5: r#"( ) "#,
            line6: r#"|/  "#,
        },
        '<' => Letter {
            line1: r#"  __ "#,
            line2: r#" / / "#,
            line3: r#"/ /  "#,
            line4: r#"\ \  "#,
            line5: r#" \_\ "#,
            line6: r#"     "#,
        },
        '=' => Letter {
            line1: r#"        "#,
            line2: r#" _____  "#,
            line3: r#"|_____| "#,
            line4: r#"|_____| "#,
            line5: r#"        "#,
            line6: r#"        "#,
        },
        '>' => Letter {
            line1: r#"__   "#,
            line2: r#"\ \  "#,
            line3: r#" \ \ "#,
            line4: r#" / / "#,
            line5: r#"/_/  "#,
            line6: r#"     "#,
        },
        '?' => Letter {
            line1: r#" ___  "#,
            line2: r#"|__ \ "#,
            line3: r#"  / / "#,
            line4: r#" |_|  "#,
            line5: r#" (_)  "#,
            line6: r#"      "#,
        },
        '@' => Letter {
            line1: r#"   ____   "#,
            line2: r#"  / __ \  "#,
            line3: r#" / / _` | "#,
            line4: r#"| | (_| | "#,
            line5: r#" \ \__,_| "#,
            line6: r#"  \____/  "#,
        },


        // big case letters
        'A' => Letter {
            line1: r#"    _     "#,
            line2: r#"   / \    "#,
            line3: r#"  / _ \   "#,
            line4: r#" / ___ \  "#,
            line5: r#"/_/   \_\ "#,
            line6: r#"          "#,
        },
        'B' => Letter {
            line1: r#" ____   "#,
            line2: r#"| __ )  "#,
            line3: r#"|  _ \  "#,
            line4: r#"| |_) | "#,
            line5: r#"|____/  "#,
            line6: r#"        "#,
        },
        'C' => Letter {
            line1: r#"  ____  "#,
            line2: r#" / ___| "#,
            line3: r#"| |     "#,
            line4: r#"| |___  "#,
            line5: r#" \____| "#,
            line6: r#"        "#,
        },
        'D' => Letter {
            line1: r#" ____   "#,
            line2: r#"|  _ \  "#,
            line3: r#"| | | | "#,
            line4: r#"| |_| | "#,
            line5: r#"|____/  "#,
            line6: r#"        "#,
        },
        'E' => Letter {
            line1: r#" _____  "#,
            line2: r#"| ____| "#,
            line3: r#"|  _|   "#,
            line4: r#"| |___  "#,
            line5: r#"|_____| "#,
            line6: r#"        "#,
        },
        'F' => Letter {
            line1: r#" _____  "#,
            line2: r#"|  ___| "#,
            line3: r#"| |_    "#,
            line4: r#"|  _|   "#,
            line5: r#"|_|     "#,
            line6: r#"        "#,
        },
        'G' => Letter {
            line1: r#"  ____  "#,
            line2: r#" / ___| "#,
            line3: r#"| |  _  "#,
            line4: r#"| |_| | "#,
            line5: r#" \____| "#,
            line6: r#"        "#,
        },
        'H' => Letter {
            line1: r#" _   _  "#,
            line2: r#"| | | | "#,
            line3: r#"| |_| | "#,
            line4: r#"|  _  | "#,
            line5: r#"|_| |_| "#,
            line6: r#"        "#,
        },
        'I' => Letter {
            line1: r#" ___  "#,
            line2: r#"|_ _| "#,
            line3: r#" | |  "#,
            line4: r#" | |  "#,
            line5: r#"|___| "#,
            line6: r#"      "#,
        },
        'J' => Letter {
            line1: r#"     _  "#,
            line2: r#"    | | "#,
            line3: r#" _  | | "#,
            line4: r#"| |_| | "#,
            line5: r#" \___/  "#,
            line6: r#"        "#,
        },
        'K' => Letter {
            line1: r#" _  __ "#,
            line2: r#"| |/ / "#,
            line3: r#"| ' /  "#,
            line4: r#"| . \  "#,
            line5: r#"|_|\_\ "#,
            line6: r#"       "#,
        },
        'L' => Letter {
            line1: r#" _      "#,
            line2: r#"| |     "#,
            line3: r#"| |     "#,
            line4: r#"| |___  "#,
            line5: r#"|_____| "#,
            line6: r#"        "#,
        },
        'M' => Letter {
            line1: r#" __  __  "#,
            line2: r#"|  \/  | "#,
            line3: r#"| |\/| | "#,
            line4: r#"| |  | | "#,
            line5: r#"|_|  |_| "#,
            line6: r#"         "#,
        },
        'N' => Letter {
            line1: r#" _   _  "#,
            line2: r#"| \ | | "#,
            line3: r#"|  \| | "#,
            line4: r#"| |\  | "#,
            line5: r#"|_| \_| "#,
            line6: r#"        "#,
        },
        'O' => Letter {
            line1: r#"  ____   "#,
            line2: r#" / __ \  "#,
            line3: r#"| |  | | "#,
            line4: r#"| |__| | "#,
            line5: r#" \____/  "#,
            line6: r#"         "#,
        },
        'P' => Letter {
            line1: r#" ____   "#,
            line2: r#"|  _ \  "#,
            line3: r#"| |_) | "#,
            line4: r#"|  __/  "#,
            line5: r#"|_|     "#,
            line6: r#"        "#,
        },
        'Q' => Letter {
            line1: r#"  ___   "#,
            line2: r#" / _ \  "#,
            line3: r#"| | | | "#,
            line4: r#"| |_| | "#,
            line5: r#" \__\_\ "#,
            line6: r#"        "#,
        },
        'R' => Letter {
            line1: r#" ____   "#,
            line2: r#"|  _ \  "#,
            line3: r#"| |_) | "#,
            line4: r#"|  _ <  "#,
            line5: r#"|_| \_\ "#,
            line6: r#"        "#,
        },
        'S' => Letter {
            line1: r#" ____   "#,
            line2: r#"/ ___|  "#,
            line3: r#"\___ \  "#,
            line4: r#" ___) | "#,
            line5: r#"|____/  "#,
            line6: r#"        "#,
        },
        'T' => Letter {
            line1: r#" _____  "#,
            line2: r#"|_   _| "#,
            line3: r#"  | |   "#,
            line4: r#"  | |   "#,
            line5: r#"  |_|   "#,
            line6: r#"        "#,
        },
        'U' => Letter {
            line1: r#" _   _  "#,
            line2: r#"| | | | "#,
            line3: r#"| | | | "#,
            line4: r#"| |_| | "#,
            line5: r#" \___/  "#,
            line6: r#"        "#,
        },
        'V' => Letter {
            line1: r#"__     __ "#,
            line2: r#"\ \   / / "#,
            line3: r#" \ \ / /  "#,
            line4: r#"  \ V /   "#,
            line5: r#"   \_/    "#,
            line6: r#"          "#,
        },
        'W' => Letter {
            line1: r#"__        __ "#,
            line2: r#"\ \      / / "#,
            line3: r#" \ \ /\ / /  "#,
            line4: r#"  \ V  V /   "#,
            line5: r#"   \_/\_/    "#,
            line6: r#"             "#,
        },
        'X' => Letter {
            line1: r#"__  __ "#,
            line2: r#"\ \/ / "#,
            line3: r#" \  /  "#,
            line4: r#" /  \  "#,
            line5: r#"/_/\_\ "#,
            line6: r#"       "#,
        },
        'Y' => Letter {
            line1: r#"__   __ "#,
            line2: r#"\ \ / / "#,
            line3: r#" \ V /  "#,
            line4: r#"  | |   "#,
            line5: r#"  |_|   "#,
            line6: r#"        "#,
        },
        'Z' => Letter {
            line1: r#" _____ "#,
            line2: r#"|__  / "#,
            line3: r#"  / /  "#,
            line4: r#" / /_  "#,
            line5: r#"/____| "#,
            line6: r#"       "#,
        },

        // [ \ ] ^ _ `
        '[' => Letter {
            line1: r#" __  "#,
            line2: r#"| _| "#,
            line3: r#"| |  "#,
            line4: r#"| |  "#,
            line5: r#"| |  "#,
            line6: r#"|__| "#,
        },
        '\\' => Letter {
            line1: r#"__     "#,
            line2: r#"\ \    "#,
            line3: r#" \ \   "#,
            line4: r#"  \ \  "#,
            line5: r#"   \_\ "#,
            line6: r#"       "#,
        },
        ']' => Letter {
            line1: r#" __  "#,
            line2: r#"|_ | "#,
            line3: r#" | | "#,
            line4: r#" | | "#,
            line5: r#" | | "#,
            line6: r#"|__| "#,
        },
        '^' => Letter {
            line1: r#" /\  "#,
            line2: r#"|/\| "#,
            line3: r#"     "#,
            line4: r#"     "#,
            line5: r#"     "#,
            line6: r#"     "#,
        },
        '_' => Letter {
            line1: r#"        "#,
            line2: r#"        "#,
            line3: r#"        "#,
            line4: r#"        "#,
            line5: r#" _____  "#,
            line6: r#"|_____| "#,
        },
        '`' => Letter {
            line1: r#" _  "#,
            line2: r#"( ) "#,
            line3: r#" \| "#,
            line4: r#"    "#,
            line5: r#"    "#,
            line6: r#"    "#,
        },

        // small case letters
        'a' => Letter {
            line1: r#"        "#,
            line2: r#"  __ _  "#,
            line3: r#" / _` | "#,
            line4: r#"| (_| | "#,
            line5: r#" \__,_| "#,
            line6: r#"        "#,
        },
        'b' => Letter {
            line1: r#" _      "#,
            line2: r#"| |__   "#,
            line3: r#"| '_ \  "#,
            line4: r#"| |_) | "#,
            line5: r#"|_.__/  "#,
            line6: r#"        "#,
        },
        'c' => Letter {
            line1: r#"        "#,
            line2: r#"  ____  "#,
            line3: r#" / ___| "#,
            line4: r#"| (___  "#,
            line5: r#" \____| "#,
            line6: r#"        "#,
        },
        'd' => Letter {
            line1: r#"     _  "#,
            line2: r#"  __| | "#,
            line3: r#" / _  | "#,
            line4: r#"| (_| | "#,
            line5: r#" \__,_| "#,
            line6: r#"        "#,
        },
        'e' => Letter {
            line1: r#"        "#,
            line2: r#"  ___   "#,
            line3: r#" / _  \ "#,
            line4: r#"|  ___/ "#,
            line5: r#" \____| "#,
            line6: r#"        "#,
        },
        'f' => Letter {
            line1: r#"  __  "#,
            line2: r#" / _| "#,
            line3: r#"| |_  "#,
            line4: r#"|  _| "#,
            line5: r#"|_|   "#,
            line6: r#"      "#,
        },
        'g' => Letter {
            line1: r#"        "#,
            line2: r#"  __ _  "#,
            line3: r#" / _` | "#,
            line4: r#"| (_| | "#,
            line5: r#" \__, | "#,
            line6: r#" |___/  "#,
        },
        'h' => Letter {
            line1: r#" _      "#,
            line2: r#"| |__   "#,
            line3: r#"| '_ \  "#,
            line4: r#"| | | | "#,
            line5: r#"|_| |_| "#,
            line6: r#"        "#,
        },
        'i' => Letter {
            line1: r#" _  "#,
            line2: r#"(_) "#,
            line3: r#"| | "#,
            line4: r#"| | "#,
            line5: r#"|_| "#,
            line6: r#"    "#,
        },
        'j' => Letter {
            line1: r#"   _  "#,
            line2: r#"  (_) "#,
            line3: r#"  | | "#,
            line4: r#"  | | "#,
            line5: r#" _/ | "#,
            line6: r#"|__/  "#,
        },
        'k' => Letter {
            line1: r#" _     "#,
            line2: r#"| | __ "#,
            line3: r#"| |/ / "#,
            line4: r#"|   <  "#,
            line5: r#"|_|\_\ "#,
            line6: r#"       "#,
        },
        'l' => Letter {
            line1: r#" _  "#,
            line2: r#"| | "#,
            line3: r#"| | "#,
            line4: r#"| | "#,
            line5: r#"|_| "#,
            line6: r#"    "#,
        },
        'm' => Letter {
            line1: r#"            "#,
            line2: r#" _ __ ___   "#,
            line3: r#"| '_ ` _ \  "#,
            line4: r#"| | | | | | "#,
            line5: r#"|_| |_| |_| "#,
            line6: r#"            "#,
        },
        'n' => Letter {
            line1: r#"        "#,
            line2: r#" _ __   "#,
            line3: r#"| '_ \  "#,
            line4: r#"| | | | "#,
            line5: r#"|_| |_| "#,
            line6: r#"        "#,
        },
        'o' => Letter {
            line1: r#"        "#,
            line2: r#"  ___   "#,
            line3: r#" / _ \  "#,
            line4: r#"| (_) | "#,
            line5: r#" \___/  "#,
            line6: r#"        "#,
        },
        'p' => Letter {
            line1: r#"        "#,
            line2: r#" _ __   "#,
            line3: r#"| '_ \  "#,
            line4: r#"| |_) | "#,
            line5: r#"| .__/  "#,
            line6: r#"|_|     "#,
        },
        'q' => Letter {
            line1: r#"        "#,
            line2: r#"  __ _  "#,
            line3: r#" / _` | "#,
            line4: r#"| (_| | "#,
            line5: r#" \__, | "#,
            line6: r#"    |_| "#,
        },
        'r' => Letter {
            line1: r#"       "#,
            line2: r#" _ __  "#,
            line3: r#"| '__| "#,
            line4: r#"| |    "#,
            line5: r#"|_|    "#,
            line6: r#"       "#,
        },
        's' => Letter {
            line1: r#"      "#,
            line2: r#"  __  "#,
            line3: r#"/ __| "#,
            line4: r#"\__ \ "#,
            line5: r#"|___/ "#,
            line6: r#"      "#,
        },
        't' => Letter {
            line1: r#" _    "#,
            line2: r#"| |_  "#,
            line3: r#"| __| "#,
            line4: r#"| |_  "#,
            line5: r#" \__| "#,
            line6: r#"      "#,
        },
        'u' => Letter {
            line1: r#"        "#,
            line2: r#" _   _  "#,
            line3: r#"| | | | "#,
            line4: r#"| |_| | "#,
            line5: r#" \__,_| "#,
            line6: r#"        "#,
        },
        'v' => Letter {
            line1: r#"        "#,
            line2: r#"__   __ "#,
            line3: r#"\ \ / / "#,
            line4: r#" \ V /  "#,
            line5: r#"  \_/   "#,
            line6: r#"        "#,
        },
        'w' => Letter {
            line1: r#"           "#,
            line2: r#"__      __ "#,
            line3: r#"\ \ /\ / / "#,
            line4: r#" \ V  V /  "#,
            line5: r#"  \_/\_/   "#,
            line6: r#"           "#,
        },
        'x' => Letter {
            line1: r#"       "#,
            line2: r#"__  __ "#,
            line3: r#"\ \/ / "#,
            line4: r#" >  <  "#,
            line5: r#"/_/\_\ "#,
            line6: r#"       "#,
        },
        'y' => Letter {
            line1: r#"        "#,
            line2: r#" _   _  "#,
            line3: r#"| | | | "#,
            line4: r#"| |_| | "#,
            line5: r#" \__, | "#,
            line6: r#" |___/  "#,
        },
        'z' => Letter {
            line1: r#"      "#,
            line2: r#" ____ "#,
            line3: r#"|_  / "#,
            line4: r#" / /  "#,
            line5: r#"/___| "#,
            line6: r#"      "#,
        },

        // { | } ~ and that's about it
        '{' => Letter {
            line1: r#"    __ "#,
            line2: r#"   / / "#,
            line3: r#"  | |  "#,
            line4: r#" < <   "#,
            line5: r#"  | |  "#,
            line6: r#"   \_\ "#,
        },
        '|' => Letter {
            line1: r#" _  "#,
            line2: r#"| | "#,
            line3: r#"| | "#,
            line4: r#"| | "#,
            line5: r#"| | "#,
            line6: r#"|_| "#,
        },
        '}' => Letter {
            line1: r#"__    "#,
            line2: r#"\ \   "#,
            line3: r#" | |  "#,
            line4: r#"  > > "#,
            line5: r#" | |  "#,
            line6: r#"/_/   "#,
        },
        '~' => Letter {
            line1: r#"      "#,
            line2: r#"      "#,
            line3: r#" /\/| "#,
            line4: r#"|/\/  "#,
            line5: r#"      "#,
            line6: r#"      "#,
        },

        // some fancy french letters
        'à' => Letter {
            line1: r#"   \_\  "#,
            line2: r#"  __ _  "#,
            line3: r#" / _` | "#,
            line4: r#"| (_| | "#,
            line5: r#" \__,_| "#,
            line6: r#"        "#,
        },
        'ç' => Letter {
            line1: r#"        "#,
            line2: r#"  ____  "#,
            line3: r#" / ___| "#,
            line4: r#"| (___  "#,
            line5: r#" \_  _| "#,
            line6: r#"   |/   "#,
        },
        'é' => Letter {
            line1: r#"    __  "#,
            line2: r#"  _/_/  "#,
            line3: r#" / _  \ "#,
            line4: r#"|  ___/ "#,
            line5: r#" \____| "#,
            line6: r#"        "#,
        },
        'è' => Letter {
            line1: r#"   __   "#,
            line2: r#"  _\ \  "#,
            line3: r#" / _  \ "#,
            line4: r#"|  ___/ "#,
            line5: r#" \____| "#,
            line6: r#"        "#,
        },
        'ê' => Letter {
            line1: r#"  /_\   "#,
            line2: r#"  ___   "#,
            line3: r#" / _  \ "#,
            line4: r#"|  ___/ "#,
            line5: r#" \____| "#,
            line6: r#"        "#,
        },
        // In case the character isn't recognised, we'll put a huge X to it
        _ => Letter {
                line1: "OO    OO",
                line2: " OO  OO ",
                line3: "  OOOO  ",
                line4: "  OOOO  ",
                line5: " OO  OO ",
                line6: "OO    OO",
            },
    }
}
